### ISSUE TITLE
A python error despite following all the installation instructions.

### ISSUE THREAD

**Issue by nikhilbhalla94** [amromics/panta#4]
When i run panta, it returns:
Traceback (most recent call last):
  File "/home/nikhil/mambaforge/envs/panta/bin/panta", line 8, in <module>
    sys.exit(main())
  File "/home/nikhil/mambaforge/envs/panta/lib/python3.10/site-packages/panta/cli.py", line 413, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

**Comment by mdcao** [comment]
Pls run panta with sub command `main` and `add`.
