### ISSUE TITLE
Error running diamond makedb

### ISSUE THREAD

**Issue by Iruj-04** [amromics/panta#5]
I encountered this error when running panta even though I followed the instructions for installation. Please help. Thank you!

01:12:34 INFO : Extract protein -- time taken 0:00:18.262128
01:12:36 INFO : Extract protein -- time taken 0:00:19.349068
01:12:42 INFO : Combine protein -- time taken 0:00:06.345076
01:12:42 INFO : Running "cd-hit -i Panta_Output_Alignment/temp/combined.faa -o Panta_Output_Alignment/temp/cd-hit_tmp.fasta -s 0.98 -c 0.98 -T 20 -M 0 -g 1 -d 256 > /dev/null
01:23:09 INFO : Run CD-HIT with 98% identity part 1 -- time taken 0:10:27.252495
01:23:11 INFO : Run CD-HIT with 98% identity part 1 -- time taken 0:10:29.013680
01:23:14 INFO : Run CD-HIT with 98% identity -- time taken 0:10:32.550829
01:23:14 INFO : len cd_hit_clusters = 765762
01:23:15 INFO : Running "diamond makedb --in Panta_Output_Alignment/temp/cd-hit.fasta -d Panta_Output_Alignment/temp/blast/diamond_db -p 20 --quiet
  File "/root/miniconda3/envs/panta/bin/diamond", line 113
    print "Diamond version %s" % (get_diamond_version())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
Traceback (most recent call last):
  File "/root/miniconda3/envs/panta/bin/panta", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/panta/lib/python3.10/site-packages/panta/cli.py", line 418, in main
    args.func(args)
  File "/root/miniconda3/envs/panta/lib/python3.10/site-packages/panta/cli.py", line 119, in run_main_pipeline
    blast_result = main_pipeline.pairwise_alignment(
  File "/root/miniconda3/envs/panta/lib/python3.10/site-packages/panta/main_pipeline.py", line 172, in pairwise_alignment
    blast_result = run_diamond(
  File "/root/miniconda3/envs/panta/lib/python3.10/site-packages/panta/main_pipeline.py", line 145, in run_diamond
    raise Exception('Error running diamond makedb')

**Comment by gavinmdouglas** [comment]
Hi there, 

@Juri04-MSc the syntax error you're getting looks like it's running Python 2 code (`print` without parantheses), but is expecting Python 3.

I am also getting a diamond makedb error, and I'm not sure what the issue is. Would a more informative error be reported if this were a memory issue?

```
12:36:36 INFO : Extract protein -- time taken 0:01:46.188577
12:38:01 INFO : Extract protein -- time taken 0:03:11.178505
12:39:43 INFO : Combine protein -- time taken 0:01:41.860539
12:39:43 INFO : Running "cd-hit -i output/Vibrio/temp/combined.faa -o output/Vibrio/temp/cd-hit_tmp.fasta -s 0.98 -c 0.98 -T 32 -M 0 -g 1 -d 256 > /dev/null
03:24:01 INFO : Run CD-HIT with 98% identity part 1 -- time taken 2:44:18.300975
03:24:10 INFO : Run CD-HIT with 98% identity part 1 -- time taken 2:44:26.783977
03:24:29 INFO : Run CD-HIT with 98% identity -- time taken 2:44:46.312728
03:24:30 INFO : len cd_hit_clusters = 1723229
03:24:30 INFO : Running "diamond makedb --in output/Vibrio/temp/cd-hit.fasta -d output/Vibrio/temp/blast/diamond_db -p 32 --quiet
03:24:40 INFO : Running "diamond blastp -q output/Vibrio/temp/cd-hit.fasta -d output/Vibrio/temp/blast/diamond_db -p 32 --evalue 1e-06 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen --max-target-seqs 2000 2> /dev/null 1> output/Vibrio/temp/blast/diamond.tsv
Traceback (most recent call last):
  File "/usr/local/usrapps/metastrain/gmdougla/conda_envs/panta/bin/panta", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/usrapps/metastrain/gmdougla/conda_envs/panta/lib/python3.13/site-packages/panta/cli.py", line 425, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/usr/local/usrapps/metastrain/gmdougla/conda_envs/panta/lib/python3.13/site-packages/panta/cli.py", line 123, in run_main_pipeline
    blast_result = main_pipeline.pairwise_alignment(
        diamond=(args.blast=='diamond'),
    ...<3 lines>...
        evalue = args.evalue,
        threads=threads)
  File "/usr/local/usrapps/metastrain/gmdougla/conda_envs/panta/lib/python3.13/site-packages/panta/main_pipeline.py", l
ine 172, in pairwise_alignment
    blast_result = run_diamond(
        database_fasta = database_fasta,
    ...<3 lines>...
        threads=threads
        )
  File "/usr/local/usrapps/metastrain/gmdougla/conda_envs/panta/lib/python3.13/site-packages/panta/main_pipeline.py", l
ine 154, in run_diamond
    raise Exception('Error running diamond makedb')
Exception: Error running diamond makedb
08:46:07 INFO : Extract protein -- time taken 0:03:03.713930
08:46:58 INFO : Extract protein -- time taken 0:03:54.249571
08:48:03 INFO : Combine protein -- time taken 0:01:05.439220
08:48:03 INFO : Running "cd-hit -i output/Vibrio/temp/combined.faa -o output/Vibrio/temp/cd-hit_tmp.fasta -s 0.98 -c 0.
98 -T 64 -M 0 -g 1 -d 256 > /dev/null
11:59:52 INFO : Run CD-HIT with 98% identity part 1 -- time taken 3:11:49.232803
11:59:59 INFO : Run CD-HIT with 98% identity part 1 -- time taken 3:11:56.116294
12:00:15 INFO : Run CD-HIT with 98% identity -- time taken 3:12:12.091659
12:00:16 INFO : len cd_hit_clusters = 1723226
12:00:16 INFO : Running "diamond makedb --in output/Vibrio/temp/cd-hit.fasta -d output/Vibrio/temp/blast/diamond_db -p
64 --quiet
12:00:22 INFO : Running "diamond blastp -q output/Vibrio/temp/cd-hit.fasta -d output/Vibrio/temp/blast/diamond_db -p 64
 --evalue 1e-06 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen sl
en --max-target-seqs 2000 2> /dev/null 1> output/Vibrio/temp/blast/diamond.tsv
```
